"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let addition = 2 + 3 + 2 + 1;
console.log(addition);
let subtraction = 10 - 2;
console.log(subtraction);
let multiplication = 4 * 2;
console.log(multiplication);
let division = 16 / 2;
console.log(division);
